import type { VionaActionRegistryEntry } from './vionaActionCapabilityTypes';

/**
 * Pack26B canonical action registry — definitions only.
 * executionEnabled and uiAffordanceAllowed are false for every entry in this pack.
 * Pack25 runtime behavior is unchanged and not wired to this registry yet.
 */
export const VIONA_ACTION_REGISTRY: readonly VionaActionRegistryEntry[] = [
  {
    actionId: 'request.status.submitted_to_triage',
    universe: 'local',
    actionFamily: 'request.status',
    displayName: 'Send to review',
    description:
      'Owner-initiated submitted → triage status transition. Pack25 reference action; registry documents existing behavior only.',
    defaultReadiness: 'staging_verified',
    allowedRoles: ['owner'],
    requiredCapabilityFlags: ['staging_verified'],
    requiredApprovals: 'none',
    auditCategory: 'action.status',
    timelineCategory: 'status_transition',
    idempotencyRequired: true,
    marketGate: 'required',
    legalGate: 'none',
    paymentGate: 'none',
    opsGate: 'required',
    sosGate: 'none',
    disabledReason: null,
    ownerFacingCopySafetyLevel: 'staging',
    executionEnabled: false,
    uiAffordanceAllowed: false,
    notes:
      'Pack25 proven reference. Registry layer does not control runtime; executionEnabled false until future pack authorizes wiring.',
  },
  {
    actionId: 'request.assign',
    universe: 'local',
    actionFamily: 'request.workflow',
    displayName: 'Assign request',
    description: 'Operator assignment workflow — future Pack27; blocked in Pack26B.',
    defaultReadiness: 'disabled',
    allowedRoles: ['operator'],
    requiredCapabilityFlags: ['disabled'],
    requiredApprovals: 'operator',
    auditCategory: 'action.assign',
    timelineCategory: 'workflow',
    idempotencyRequired: true,
    marketGate: 'blocked',
    legalGate: 'none',
    paymentGate: 'none',
    opsGate: 'required',
    sosGate: 'none',
    disabledReason: 'Future-blocked — Pack27 authorization required.',
    ownerFacingCopySafetyLevel: 'demo',
    executionEnabled: false,
    uiAffordanceAllowed: false,
    notes: 'Definition only; not executable.',
  },
  {
    actionId: 'request.confirm',
    universe: 'local',
    actionFamily: 'request.workflow',
    displayName: 'Confirm request',
    description: 'Owner/operator confirm workflow — future Pack27; blocked in Pack26B.',
    defaultReadiness: 'disabled',
    allowedRoles: ['owner', 'operator'],
    requiredCapabilityFlags: ['disabled'],
    requiredApprovals: 'owner',
    auditCategory: 'action.confirm',
    timelineCategory: 'workflow',
    idempotencyRequired: true,
    marketGate: 'blocked',
    legalGate: 'none',
    paymentGate: 'none',
    opsGate: 'required',
    sosGate: 'none',
    disabledReason: 'Future-blocked — Pack27 authorization required.',
    ownerFacingCopySafetyLevel: 'demo',
    executionEnabled: false,
    uiAffordanceAllowed: false,
    notes: 'Definition only; not executable.',
  },
  {
    actionId: 'request.cancel',
    universe: 'local',
    actionFamily: 'request.workflow',
    displayName: 'Cancel request',
    description: 'Owner/operator cancel workflow — future Pack27; blocked in Pack26B.',
    defaultReadiness: 'disabled',
    allowedRoles: ['owner', 'operator'],
    requiredCapabilityFlags: ['disabled'],
    requiredApprovals: 'owner',
    auditCategory: 'action.cancel',
    timelineCategory: 'workflow',
    idempotencyRequired: true,
    marketGate: 'blocked',
    legalGate: 'none',
    paymentGate: 'none',
    opsGate: 'required',
    sosGate: 'none',
    disabledReason: 'Future-blocked — Pack27 authorization required.',
    ownerFacingCopySafetyLevel: 'demo',
    executionEnabled: false,
    uiAffordanceAllowed: false,
    notes: 'Definition only; not executable.',
  },
  {
    actionId: 'booking.request',
    universe: 'local',
    actionFamily: 'booking',
    displayName: 'Booking request',
    description: 'Booking intent — future-blocked; no fulfillment claims.',
    defaultReadiness: 'disabled',
    allowedRoles: ['owner'],
    requiredCapabilityFlags: ['disabled'],
    requiredApprovals: 'owner',
    auditCategory: 'action.booking',
    timelineCategory: 'booking',
    idempotencyRequired: true,
    marketGate: 'blocked',
    legalGate: 'required',
    paymentGate: 'blocked',
    opsGate: 'required',
    sosGate: 'none',
    disabledReason: 'Future-blocked — booking lane not authorized.',
    ownerFacingCopySafetyLevel: 'demo',
    executionEnabled: false,
    uiAffordanceAllowed: false,
    notes: 'Definition only; not executable.',
  },
  {
    actionId: 'payment.intent',
    universe: 'account',
    actionFamily: 'payment',
    displayName: 'Payment intent',
    description: 'Payment-gated action — highest gate; blocked in Pack26B.',
    defaultReadiness: 'disabled',
    allowedRoles: ['owner'],
    requiredCapabilityFlags: ['disabled'],
    requiredApprovals: 'owner',
    auditCategory: 'action.payment',
    timelineCategory: 'payment',
    idempotencyRequired: true,
    marketGate: 'blocked',
    legalGate: 'required',
    paymentGate: 'blocked',
    opsGate: 'required',
    sosGate: 'none',
    disabledReason: 'Future-blocked / payment-gated — payment rails not authorized.',
    ownerFacingCopySafetyLevel: 'demo',
    executionEnabled: false,
    uiAffordanceAllowed: false,
    notes: 'Definition only; not executable.',
  },
  {
    actionId: 'sos.assist',
    universe: 'sos',
    actionFamily: 'sos',
    displayName: 'SOS assist',
    description: 'Emergency-blocked safety guidance — no dispatch claims.',
    defaultReadiness: 'disabled',
    allowedRoles: ['owner', 'emergency_reviewer'],
    requiredCapabilityFlags: ['disabled'],
    requiredApprovals: 'emergency_reviewer',
    auditCategory: 'action.sos',
    timelineCategory: 'safety',
    idempotencyRequired: true,
    marketGate: 'blocked',
    legalGate: 'blocked',
    paymentGate: 'none',
    opsGate: 'blocked',
    sosGate: 'blocked',
    disabledReason: 'Future-blocked / highest-gate — emergency-blocked; no dispatch proof.',
    ownerFacingCopySafetyLevel: 'demo',
    executionEnabled: false,
    uiAffordanceAllowed: false,
    notes: 'Definition only; not executable.',
  },
  {
    actionId: 'wallet.adjustment',
    universe: 'account',
    actionFamily: 'wallet',
    displayName: 'Wallet adjustment',
    description: 'Wallet mutation — highest gate; blocked in Pack26B.',
    defaultReadiness: 'disabled',
    allowedRoles: ['owner', 'admin'],
    requiredCapabilityFlags: ['disabled'],
    requiredApprovals: 'owner',
    auditCategory: 'action.wallet',
    timelineCategory: 'wallet',
    idempotencyRequired: true,
    marketGate: 'blocked',
    legalGate: 'required',
    paymentGate: 'blocked',
    opsGate: 'required',
    sosGate: 'none',
    disabledReason: 'Future-blocked / highest-gate — wallet lane not authorized.',
    ownerFacingCopySafetyLevel: 'demo',
    executionEnabled: false,
    uiAffordanceAllowed: false,
    notes: 'Definition only; not executable.',
  },
  {
    actionId: 'live_ai.action',
    universe: 'cross_universe',
    actionFamily: 'live_ai',
    displayName: 'Live AI action',
    description: 'Autonomous live AI action — highest gate; blocked in Pack26B.',
    defaultReadiness: 'disabled',
    allowedRoles: ['owner', 'operator'],
    requiredCapabilityFlags: ['disabled'],
    requiredApprovals: 'operator',
    auditCategory: 'action.live_ai',
    timelineCategory: 'live_ai',
    idempotencyRequired: true,
    marketGate: 'blocked',
    legalGate: 'blocked',
    paymentGate: 'blocked',
    opsGate: 'blocked',
    sosGate: 'none',
    disabledReason: 'Future-blocked / highest-gate — live AI lane not authorized.',
    ownerFacingCopySafetyLevel: 'demo',
    executionEnabled: false,
    uiAffordanceAllowed: false,
    notes: 'Definition only; not executable.',
  },
] as const;

export const VIONA_ACTION_REGISTRY_BY_ID: Readonly<Record<string, VionaActionRegistryEntry>> =
  Object.freeze(
    Object.fromEntries(VIONA_ACTION_REGISTRY.map((entry) => [entry.actionId, entry])),
  );
