import type { AiCostFeatureId, AiCostGuardDefinition } from './aiCostTypes';

/**
 * Static guard definitions for product, ops, and UI — not live metering.
 * Numeric caps are planning defaults until per-tenant metering ships.
 */
export const AI_COST_GUARD_REGISTRY: Readonly<Record<AiCostFeatureId, AiCostGuardDefinition>> = {
  aiReceptionistDemo: {
    featureId: 'aiReceptionistDemo',
    labelKey: 'aiCost.feature.aiReceptionistDemo',
    status: 'demoOnly',
    includedUsage: 30,
    hardCap: 60,
    unit: 'request',
    resetWindow: 'session',
    requiresUpgrade: false,
    requiresHumanApproval: false,
    autoPauseOnCap: true,
    providerCostRisk: 'low',
    productionReady: false,
    notesKey: 'aiCost.notes.seeRunbook',
  },
  aiReceptionistPilot: {
    featureId: 'aiReceptionistPilot',
    labelKey: 'aiCost.feature.aiReceptionistPilot',
    status: 'pilotOnly',
    includedUsage: 200,
    hardCap: 500,
    unit: 'request',
    resetWindow: 'monthly',
    requiresUpgrade: false,
    requiresHumanApproval: true,
    autoPauseOnCap: true,
    providerCostRisk: 'medium',
    productionReady: false,
    notesKey: 'aiCost.notes.seeRunbook',
  },
  b2cAiCallAssistant: {
    featureId: 'b2cAiCallAssistant',
    labelKey: 'aiCost.feature.b2cAiCallAssistant',
    status: 'gated',
    includedUsage: 45,
    hardCap: 120,
    unit: 'minute',
    resetWindow: 'monthly',
    requiresUpgrade: true,
    requiresHumanApproval: true,
    autoPauseOnCap: true,
    providerCostRisk: 'high',
    productionReady: false,
    notesKey: 'aiCost.notes.seeRunbook',
  },
  leonaAssistant: {
    featureId: 'leonaAssistant',
    labelKey: 'aiCost.feature.leonaAssistant',
    status: 'active',
    includedUsage: 60,
    hardCap: 120,
    unit: 'message',
    resetWindow: 'daily',
    requiresUpgrade: false,
    requiresHumanApproval: false,
    autoPauseOnCap: true,
    providerCostRisk: 'medium',
    productionReady: false,
    notesKey: 'aiCost.notes.seeRunbook',
  },
  minhKhangTranslator: {
    featureId: 'minhKhangTranslator',
    labelKey: 'aiCost.feature.minhKhangTranslator',
    status: 'gated',
    includedUsage: 40,
    hardCap: 80,
    unit: 'request',
    resetWindow: 'daily',
    requiresUpgrade: true,
    requiresHumanApproval: false,
    autoPauseOnCap: true,
    providerCostRisk: 'medium',
    productionReady: false,
    notesKey: 'aiCost.notes.seeRunbook',
  },
  documentScanner: {
    featureId: 'documentScanner',
    labelKey: 'aiCost.feature.documentScanner',
    status: 'gated',
    includedUsage: 15,
    hardCap: 35,
    unit: 'document',
    resetWindow: 'monthly',
    requiresUpgrade: true,
    requiresHumanApproval: false,
    autoPauseOnCap: true,
    providerCostRisk: 'high',
    productionReady: false,
    notesKey: 'aiCost.notes.seeRunbook',
  },
  liveInterpreter: {
    featureId: 'liveInterpreter',
    labelKey: 'aiCost.feature.liveInterpreter',
    status: 'pilotOnly',
    includedUsage: 30,
    hardCap: 90,
    unit: 'minute',
    resetWindow: 'weekly',
    requiresUpgrade: true,
    requiresHumanApproval: true,
    autoPauseOnCap: true,
    providerCostRisk: 'high',
    productionReady: false,
    notesKey: 'aiCost.notes.seeRunbook',
  },
  copilot: {
    featureId: 'copilot',
    labelKey: 'aiCost.feature.copilot',
    status: 'gated',
    includedUsage: 50,
    hardCap: 100,
    unit: 'message',
    resetWindow: 'daily',
    requiresUpgrade: false,
    requiresHumanApproval: false,
    autoPauseOnCap: true,
    providerCostRisk: 'medium',
    productionReady: false,
    notesKey: 'aiCost.notes.seeRunbook',
  },
  outboundMarketingDraft: {
    featureId: 'outboundMarketingDraft',
    labelKey: 'aiCost.feature.outboundMarketingDraft',
    status: 'frozen',
    includedUsage: 0,
    hardCap: 0,
    unit: 'request',
    resetWindow: 'none',
    requiresUpgrade: true,
    requiresHumanApproval: true,
    autoPauseOnCap: true,
    providerCostRisk: 'high',
    productionReady: false,
    notesKey: 'aiCost.notes.seeRunbook',
  },
};
