import type { VionaRequestRecord } from './vionaRequestTypes';

/** Sample fixtures for read-only inbox preview. Not live data. */
export const vionaRequestReadOnlyFixtures: readonly VionaRequestRecord[] = [
  {
    id: 'req-local-draft-001',
    universe: 'local',
    intent: 'serviceHelp',
    status: 'draft',
    riskLevel: 'low',
    humanConfirmation: 'notRequired',
    createdBy: 'user',
    updatedBy: 'user',
    auditReason: 'Local service help draft — preview only, not submitted.',
  },
  {
    id: 'req-travel-submitted-002',
    universe: 'travel',
    intent: 'travelHelp',
    status: 'submitted',
    riskLevel: 'medium',
    humanConfirmation: 'notRequired',
    createdBy: 'user',
    updatedBy: 'system',
    auditReason: 'Travel itinerary question — request submitted; no payment captured.',
  },
  {
    id: 'req-business-triage-003',
    universe: 'business',
    intent: 'merchantHelp',
    status: 'triage',
    riskLevel: 'medium',
    humanConfirmation: 'notRequired',
    createdBy: 'user',
    updatedBy: 'admin',
    auditReason: 'Merchant catalog import question — ops triage queue; not booking confirmed.',
  },
  {
    id: 'req-account-needs-confirm-004',
    universe: 'account',
    intent: 'profileHelp',
    status: 'needsHumanConfirmation',
    riskLevel: 'high',
    humanConfirmation: 'required',
    createdBy: 'user',
    updatedBy: 'aiAssistant',
    auditReason: 'Profile data correction — human confirmation required before any account change.',
  },
  {
    id: 'req-academy-sent-partner-005',
    universe: 'academy',
    intent: 'learningHelp',
    status: 'sentToPartner',
    riskLevel: 'low',
    humanConfirmation: 'confirmed',
    createdBy: 'user',
    updatedBy: 'admin',
    auditReason: 'Course enrollment inquiry sent to partner — preview only; not booking confirmed.',
  },
  {
    id: 'req-local-partner-responded-006',
    universe: 'local',
    intent: 'serviceHelp',
    status: 'partnerResponded',
    riskLevel: 'medium',
    humanConfirmation: 'notRequired',
    createdBy: 'user',
    updatedBy: 'partner',
    auditReason: 'Partner response received for local repair quote — not booking confirmed.',
  },
  {
    id: 'req-business-completed-007',
    universe: 'business',
    intent: 'wholesaleInquiry',
    status: 'completed',
    riskLevel: 'low',
    humanConfirmation: 'confirmed',
    createdBy: 'merchant',
    updatedBy: 'admin',
    auditReason: 'Wholesale inquiry closed — completed is not settled; no payout completed.',
  },
  {
    id: 'req-travel-cancelled-008',
    universe: 'travel',
    intent: 'draftRequest',
    status: 'cancelled',
    riskLevel: 'low',
    humanConfirmation: 'declined',
    createdBy: 'user',
    updatedBy: 'user',
    auditReason: 'User cancelled travel help draft — no ticket booked.',
  },
  {
    id: 'req-sos-failed-009',
    universe: 'sos',
    intent: 'safetyGuidance',
    status: 'failed',
    riskLevel: 'restricted',
    humanConfirmation: 'required',
    createdBy: 'user',
    updatedBy: 'system',
    auditReason: 'SOS guidance handoff failed — no SOS dispatch; SOS guidance only.',
  },
] as const;

export function getVionaRequestReadOnlyFixtures(): readonly VionaRequestRecord[] {
  return vionaRequestReadOnlyFixtures;
}
