import type { MiniAppDefinition, MiniAppId } from './miniAppTypes';

/**
 * Single source of truth for mini-app metadata (VIONA Companion OS / blueprint V2).
 * Route strings: `Tabs/<TabRoute>` for bottom tabs; otherwise stack keys from `RootStackParamList`.
 */
export const MINI_APP_REGISTRY: Readonly<Record<MiniAppId, MiniAppDefinition>> = {
  hub: {
    id: 'hub',
    universe: 'hub',
    nameKey: 'miniapps.hub.name',
    descriptionKey: 'miniapps.hub.description',
    route: 'Tabs/TabHome',
    status: 'active',
    featureFlag: 'hubEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: [],
    dataDependencies: ['auth.session'],
    monetizationModel: 'free',
    riskLevel: 'low',
    readiness: 'ready',
    primaryCtaKey: 'miniapps.hub.cta',
  },
  local: {
    id: 'local',
    universe: 'local',
    nameKey: 'miniapps.local.name',
    descriptionKey: 'miniapps.local.description',
    route: 'Tabs/TabLocal',
    status: 'lite',
    featureFlag: 'localEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: [],
    dataDependencies: ['auth.session', 'merchants.directory'],
    monetizationModel: 'transaction_fee',
    riskLevel: 'medium',
    readiness: 'ready',
    primaryCtaKey: 'miniapps.local.cta',
  },
  booking: {
    id: 'booking',
    universe: 'local',
    nameKey: 'miniapps.booking.name',
    descriptionKey: 'miniapps.booking.description',
    route: 'Tabs/TabLocal',
    status: 'lite',
    featureFlag: 'bookingEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: [],
    dataDependencies: ['auth.session', 'bookings.api'],
    monetizationModel: 'transaction_fee',
    riskLevel: 'medium',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.booking.cta',
  },
  merchantDashboard: {
    id: 'merchantDashboard',
    universe: 'merchant',
    nameKey: 'miniapps.merchantDashboard.name',
    descriptionKey: 'miniapps.merchantDashboard.description',
    route: 'Tabs/TabMerchant',
    status: 'lite',
    featureFlag: 'merchantDashboardEnabled',
    requiredRoles: ['merchant'],
    permissions: [],
    dataDependencies: ['auth.session', 'merchant.tenant'],
    monetizationModel: 'saas',
    riskLevel: 'financial',
    readiness: 'ready',
    primaryCtaKey: 'miniapps.merchantDashboard.cta',
  },
  b2bAiReceptionist: {
    id: 'b2bAiReceptionist',
    universe: 'merchant',
    nameKey: 'miniapps.b2bAiReceptionist.name',
    descriptionKey: 'miniapps.b2bAiReceptionist.description',
    route: 'AiReceptionistSetupChecklist',
    status: 'pilot',
    featureFlag: 'b2bAiReceptionistDemoEnabled',
    requiredRoles: ['merchant'],
    permissions: ['microphone'],
    dataDependencies: ['auth.session', 'merchant.tenant', 'ai.policy'],
    monetizationModel: 'saas',
    riskLevel: 'ai',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.b2bAiReceptionist.cta',
  },
  b2cAiCallAssistant: {
    id: 'b2cAiCallAssistant',
    universe: 'hub',
    nameKey: 'miniapps.b2cAiCallAssistant.name',
    descriptionKey: 'miniapps.b2cAiCallAssistant.description',
    route: 'LeonaCall',
    status: 'demo',
    featureFlag: 'leonaAssistantEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: ['microphone'],
    dataDependencies: ['auth.session', 'ai.call'],
    monetizationModel: 'credits',
    riskLevel: 'ai',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.b2cAiCallAssistant.cta',
  },
  travel: {
    id: 'travel',
    universe: 'travel',
    nameKey: 'miniapps.travel.name',
    descriptionKey: 'miniapps.travel.description',
    route: 'Tabs/TabTravel',
    status: 'lite',
    featureFlag: 'travelLiteEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: [],
    dataDependencies: ['auth.session', 'travel.content'],
    monetizationModel: 'transaction_fee',
    riskLevel: 'medium',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.travel.cta',
  },
  travelOutbound: {
    id: 'travelOutbound',
    universe: 'travel',
    nameKey: 'miniapps.travelOutbound.name',
    descriptionKey: 'miniapps.travelOutbound.description',
    route: 'Tabs/TabTravel',
    status: 'lite',
    featureFlag: 'travelLiteEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: [],
    dataDependencies: ['auth.session', 'travel.content'],
    monetizationModel: 'transaction_fee',
    riskLevel: 'medium',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.travelOutbound.cta',
  },
  travelInboundVietnam: {
    id: 'travelInboundVietnam',
    universe: 'travel',
    nameKey: 'miniapps.travelInboundVietnam.name',
    descriptionKey: 'miniapps.travelInboundVietnam.description',
    route: 'Tabs/TabTravel',
    status: 'lite',
    featureFlag: 'travelLiteEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: [],
    dataDependencies: ['auth.session', 'travel.content'],
    monetizationModel: 'transaction_fee',
    riskLevel: 'medium',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.travelInboundVietnam.cta',
  },
  travelReturnToVietnam: {
    id: 'travelReturnToVietnam',
    universe: 'travel',
    nameKey: 'miniapps.travelReturnToVietnam.name',
    descriptionKey: 'miniapps.travelReturnToVietnam.description',
    route: 'Tabs/TabTravel',
    status: 'lite',
    featureFlag: 'travelLiteEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: [],
    dataDependencies: ['auth.session', 'travel.content'],
    monetizationModel: 'transaction_fee',
    riskLevel: 'medium',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.travelReturnToVietnam.cta',
  },
  academy: {
    id: 'academy',
    universe: 'academy',
    nameKey: 'miniapps.academy.name',
    descriptionKey: 'miniapps.academy.description',
    route: 'Tabs/TabAi',
    status: 'lite',
    featureFlag: 'academyLiteEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: [],
    dataDependencies: ['auth.session', 'academy.content'],
    monetizationModel: 'subscription',
    riskLevel: 'ai',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.academy.cta',
  },
  leonaAssistant: {
    id: 'leonaAssistant',
    universe: 'academy',
    nameKey: 'miniapps.leonaAssistant.name',
    descriptionKey: 'miniapps.leonaAssistant.description',
    route: 'LeonaCall',
    status: 'lite',
    featureFlag: 'leonaAssistantEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: ['microphone'],
    dataDependencies: ['auth.session', 'ai.leona'],
    monetizationModel: 'credits',
    riskLevel: 'ai',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.leonaAssistant.cta',
  },
  minhKhangTranslator: {
    id: 'minhKhangTranslator',
    universe: 'academy',
    nameKey: 'miniapps.minhKhangTranslator.name',
    descriptionKey: 'miniapps.minhKhangTranslator.description',
    route: 'LiveInterpreter',
    status: 'beta',
    featureFlag: 'aiReceptionistEnabled',
    requiredRoles: ['b2c', 'merchant', 'broker', 'admin'],
    permissions: ['camera', 'microphone'],
    dataDependencies: ['auth.session', 'ai.minhKhang'],
    monetizationModel: 'credits',
    riskLevel: 'ai',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.minhKhangTranslator.cta',
  },
  brokerQr: {
    id: 'brokerQr',
    universe: 'income',
    nameKey: 'miniapps.brokerQr.name',
    descriptionKey: 'miniapps.brokerQr.description',
    route: 'Tabs/TabQr',
    status: 'gated',
    featureFlag: 'brokerQrEnabled',
    requiredRoles: ['broker'],
    permissions: [],
    dataDependencies: ['auth.session', 'broker.attribution'],
    monetizationModel: 'transaction_fee',
    riskLevel: 'financial',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.brokerQr.cta',
  },
  admin: {
    id: 'admin',
    universe: 'admin',
    nameKey: 'miniapps.admin.name',
    descriptionKey: 'miniapps.admin.description',
    route: 'Tabs/TabCommandCenter',
    status: 'gated',
    requiredRoles: ['admin'],
    permissions: [],
    dataDependencies: ['auth.session', 'admin.ops'],
    monetizationModel: 'none',
    riskLevel: 'high',
    readiness: 'partial',
    primaryCtaKey: 'miniapps.admin.cta',
  },
};

export const MINI_APP_IDS: readonly MiniAppId[] = [
  'hub',
  'local',
  'booking',
  'merchantDashboard',
  'b2bAiReceptionist',
  'b2cAiCallAssistant',
  'travel',
  'travelOutbound',
  'travelInboundVietnam',
  'travelReturnToVietnam',
  'academy',
  'leonaAssistant',
  'minhKhangTranslator',
  'brokerQr',
  'admin',
];

export function isMiniAppId(value: string): value is MiniAppId {
  return Object.prototype.hasOwnProperty.call(MINI_APP_REGISTRY, value);
}

export function getMiniAppDefinition(id: string): MiniAppDefinition | undefined {
  if (!isMiniAppId(id)) return undefined;
  return MINI_APP_REGISTRY[id];
}
